# Generated by Django 5.0.6 on 2024-06-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='name',
            new_name='title',
        ),
    ]
