# Generated by Django 5.0.6 on 2024-06-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_name_adventure_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_first_name', models.CharField(max_length=50)),
                ('char_last_name', models.CharField(max_length=50)),
                ('char_age', models.IntegerField()),
                ('char_sex', models.IntegerField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.adventure')),
            ],
        ),
    ]
